media:
  input: assets/img

settings:
  url: https://mayankvikash.github.io 

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{slug}.md"
    links:
      - label: View Post
        url: /posts/{slug}/
    default:
      layout: post 
    fields:
      - name: title
        type: string
        label: Post Title
        required: true
      - name: date
        type: date
        label: Publish Date
        required: true
        options:
          time: true
          format: "yyyy-MM-dd HH:mm:ss xxxxx"
      - name: description
        type: string
        label: Short Description (SEO)
      - name: categories
        type: list
        label: Categories
        description: "Max 2. Example: Python"
      - name: tags
        type: list
        label: Tags
        description: "Add tags individually."
      - name: body
        type: rich-text
        label: Write your content here